<?php include APPLICATION_PATH.'/application/views/admin/head.phtml'?>

<body class="login-body">

<div class="container">

    <form class="form-signin" action="/admin_login/login" method="post">
        <div class="form-signin-heading text-center">
            <h1 class="sign-title">登录</h1>
            <img src="/admin/images/login-logo.png" alt=""/>
        </div>
        <div class="login-wrap">
            <input type="text" class="form-control" placeholder="账号" autofocus name="email" required>
            <input type="password" class="form-control" placeholder="密码" name="password" required>
            <button class="btn btn-lg btn-login btn-block" type="submit">
                <i class="fa fa-check"></i>
            </button>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> 记住密码
                <span class="pull-right">
                    <a data-toggle="modal" href="#myModal">忘记密码</a>
                </span>
            </label>
        </div>
    </form>

</div>
<script src="/admin/js/jquery-1.10.2.min.js"></script>
<script src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/modernizr.min.js"></script>
</body>
</html>
