<?php include APPLICATION_PATH.'/application/views/admin/head.phtml'?>

<body class="sticky-header">

<section>
    <!-- left side start-->
    <?php include APPLICATION_PATH.'/application/views/admin/left.phtml'?>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content" >

        <!-- header section start-->
        <?php include APPLICATION_PATH.'/application/views/admin/header.phtml'?>
        <!-- header section end-->

        <!--body wrapper start-->
        <div class="wrapper">
            <div class="row">
                <div class="col-sm-12">
                    <section class="panel">
                        <header class="panel-heading">
                            Responsive table
                        <span class="tools pull-right">
                            <a href="javascript:;" class="fa fa-chevron-down"></a>
                            <a href="javascript:;" class="fa fa-times"></a>
                         </span>
                        </header>
                        <div class="panel-body">
                            <section id="unseen">
                                <table class="table table-bordered table-striped table-condensed">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>邮箱</th>
                                        <th class="numeric">电话</th>
                                        <th class="numeric">昵称</th>
                                        <th class="numeric">状态</th>
                                        <th class="numeric">头像</th>
                                        <th class="numeric">设置</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    <tr>
                                        <td>AAC</td>
                                        <td>AUSTRALIAN AGRICULTURAL COMPANY LIMITED.</td>
                                        <td class="numeric">$1.38</td>
                                        <td class="numeric">-0.01</td>
                                        <td class="numeric">-0.36%</td>
                                        <td class="numeric">$1.39</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-danger" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>AAD</td>
                                        <td>ARDENT LEISURE GROUP</td>
                                        <td class="numeric">$1.15</td>
                                        <td class="numeric">  +0.02</td>
                                        <td class="numeric">1.32%</td>
                                        <td class="numeric">$1.14</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>AAX</td>
                                        <td>AUSENCO LIMITED</td>
                                        <td class="numeric">$4.00</td>
                                        <td class="numeric">-0.04</td>
                                        <td class="numeric">-0.99%</td>
                                        <td class="numeric">$4.01</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>ABC</td>
                                        <td>ADELAIDE BRIGHTON LIMITED</td>
                                        <td class="numeric">$3.00</td>
                                        <td class="numeric">  +0.06</td>
                                        <td class="numeric">2.04%</td>
                                        <td class="numeric">$2.98</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>ABP</td>
                                        <td>ABACUS PROPERTY GROUP</td>
                                        <td class="numeric">$1.91</td>
                                        <td class="numeric">0.00</td>
                                        <td class="numeric">0.00%</td>
                                        <td class="numeric">$1.92</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>

                                    <tr>
                                        <td>ADU</td>
                                        <td>ADAMUS RESOURCES LIMITED</td>
                                        <td class="numeric">$0.72</td>
                                        <td class="numeric">0.00</td>
                                        <td class="numeric">0.00%</td>
                                        <td class="numeric">$0.73</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>AGG</td>
                                        <td>ANGLOGOLD ASHANTI LIMITED</td>
                                        <td class="numeric">$7.81</td>
                                        <td class="numeric">-0.22</td>
                                        <td class="numeric">-2.74%</td>
                                        <td class="numeric">$7.82</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>AGK</td>
                                        <td>AGL ENERGY LIMITED</td>
                                        <td class="numeric">$13.82</td>
                                        <td class="numeric">  +0.02</td>
                                        <td class="numeric">0.14%</td>
                                        <td class="numeric">$13.83</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>AGO</td>
                                        <td>ATLAS IRON LIMITED</td>
                                        <td class="numeric">$3.17</td>
                                        <td class="numeric">-0.02</td>
                                        <td class="numeric">-0.47%</td>
                                        <td class="numeric">$3.11</td>
                                        <td class="numeric">
                                            <button class="btn btn-info" type="button">编辑</button>
                                            <button class="btn btn-info" type="button">删除</button>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table>
                            </section>
                        </div>
                    </section>
                    <div class="">
                        <ul class="pagination">
                            <li><a href="#">«</a></li>
                            <li><a href="#">1</a></li>
                            <li><a href="#">2</a></li>
                            <li><a href="#">3</a></li>
                            <li class="active"><a href="#">4</a></li>
                            <li><a href="#">5</a></li>
                            <li><a href="#">»</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <!--body wrapper end-->

        <!--footer section start-->
        <?php include APPLICATION_PATH.'/application/views/admin/footer.phtml'?>
        <!--footer section end-->


    </div>
    <!-- main content end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<script src="/admin/js/jquery-1.10.2.min.js"></script>
<script src="/admin/js/jquery-ui-1.9.2.custom.min.js"></script>
<script src="/admin/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/modernizr.min.js"></script>
<script src="/admin/js/jquery.nicescroll.js"></script>

<!--common scripts for all pages-->
<script src="/admin/js/scripts.js"></script>

</body>
</html>
