<?php include APPLICATION_PATH.'/application/views/header.phtml'?>
<div id="banner">
    <div style="background-image:url(/img/020banner.jpg)" class="banner"></div>
</div>
<div class="heading s5 gray">
    <h2>业务团队<small>Business team</small></h2>
    <div class="line"></div>
</div>
<section id="sub020-1" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic1.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num1">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-2" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic2.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num2">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-3" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic3.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num3">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-4" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic4.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num4">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-5" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic5.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num5">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-6" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic6.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num6">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<section id="sub020-7" class="tm-main">
    <div class="container">
        <div class="tm-contain clearfix">
            <div class="tm-left">
                <div class="img zoom"><img src="/img/020pic7.jpg"/></div>
            </div>
            <div class="tm-right">
                <div class="desc">
                    <h3 class="num7">金融行业的调研分</h3>
                    <p>乾道金融研究院是乾道投资控股集团有限公司下属职能部门，主要通过对于金融行业的调研分析，建立资料库，为公司的投资策略提供有力帮助。乾道金融研究院主要分为宏观经济研究中心、产业经济研究中心、数量经济研究中心、对外合作交流中心四个部门。</p>
                    <p>乾道金融研究院自成立以来与各大机构以及国内外知名专家合作举办了几十场论坛以及讨论会，对国内外经济发展趋势以及私募基金的未来发展进行深入研究，为公司发展及与同行业沟通建立起了有效的渠道。</p>
                </div>
            </div>
        </div>
        <div class="tm-items">
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
            <div class="tm-item">
                <div class="img zoom"><img src="/img/020tm.jpg"/></div>
                <div class="detail">
                    <p><strong>销售明星：</strong>王小刚</p>
                    <p><strong>职位：</strong>经理</p>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include APPLICATION_PATH.'/application/views/footer.phtml'?>
<script>
    $(document).ready(function(){
        $('.el').dotdotdot({
            ellipsis: '. . . ',
            watch: "window",
            wrap: 'letter',
        });
    })
</script>
</body>
</html>