<?php include APPLICATION_PATH.'/application/views/header.phtml'?>
<div id="banner">
    <div style="background-image:url(/img/020banner.jpg)" class="banner"></div>
</div>
<div class="heading s5 gray">
    <h2>产品中心<small>Product Center</small></h2>
    <div class="line"></div>
</div>
<section id="sub021" class="gray">
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                <div class="pc-item">
                    <div class="img zoom"><a href="#"><img src="/img/021pic.jpg"/></a></div>
                    <h3><a href="#">财富产品</a><span class="date">2015/06/03</span></h3>
                    <p class="el">乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的乾道集团凭借旗下永利宝与乾道金融两大在线投资理财平台，在汲取国外互联网金融经验后在汲取国外互联网，基于中国国情，首次提出了创新概念的情，首次提出了创新概念的<a href="#" class="readmore">了解更多 <i class="fa fa-angle-double-right"></i></a></p>
                </div>
            </div>
        </div>
        <div class="space30"></div>
        <div class="page">
            <ul>
                <li class="first"><a href="#">首页</a></li>
                <li class="prev"><a href="#">上一页</a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li class="next"><a href="#">下一页</a></li>
                <li class="last"><a href="#">末页</a></li>
            </ul>
        </div>
        <div class="space30"></div>
    </div>
</section>
<?php include APPLICATION_PATH.'/application/views/footer.phtml'?>
<script>
    $(document).ready(function(){
        $('.el').dotdotdot({
            after: "a.readmore",
            watch: "window",
            wrap: 'letter',
        });
    })
</script>
</body>
</html>