<div id="footer">
    <footer>
        <div class="container clearfix">
            <ul class="footerlink">
                <li><a href="#">产品及服务</a></li>
                <li><a href="#">安全保障</a></li>
                <li><a href="#">乾道研究</a></li>
                <li><a href="#">财富俱乐部</a></li>
                <li><a href="#">媒体中心</a></li>
                <li><a href="#">关于我们</a></li>
            </ul>
            <ul class="info">
                <li><span>乾道财富资产管理（北京）有限公司 </span></li>
                <li><span>京ICP备13038739号 </span></li>
                <li><span>Copyright  2014  <a href="http://bbctop.com">Powered  by  BBCtop.com</a></span></li>
            </ul>
        </div>
    </footer>
    <div class="loginModal">
        <div class="modal-overlay trans"></div>
        <div class="modal-container trans">
            <div id="login" class="modal-main trans show on">
                <div class="modal-heading"><a href="javascript:void(0)" class="close-modal"></a>
                    <h2>登录 SIGN IN        </h2>
                </div>
                <div class="modal-content">
                    <div class="login-form">
                        <form id="" method="" action="">
                            <div class="logbox">
                                <label class="tit">账号 :</label>
                                <input type="text" class="ipt"/>
                            </div>
                            <div class="logbox">
                                <label class="tit">密码 :</label>
                                <input type="password" class="ipt"/>
                            </div>
                            <div class="logbox">
                                <div class="clearfix">
                                    <label class="fl">
                                        <input type="checkbox" class="ckb"/> 记住密码
                                    </label><a id="forgot-btn" href="#" class="fr">密码找回</a>
                                </div>
                                <button type="submit" class="btn red">立即登录</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div id="forgot" class="modal-main trans hide">
                <div class="modal-heading"><a href="javascript:void(0)" class="close-modal"></a>
                    <h2>密码找回 Password retrieve        </h2>
                </div>
                <div class="modal-content">
                    <div class="forgot">
                        <p>请联系管理员重置密码</p>
                        <p class="big">联系方式：<span>18201596002</span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="imgModal"></div>
    <script src="/js/jquery-1.11.2.min.js"></script>
    <script src="/js/main-script.min.js"></script>
    <script src="/js/footmenu.js"></script>
    <script src="/js/loginmodal.js"></script>
</div>