<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no"/>
    <title>乾道集团</title>
    <link href="/css/style.css" rel="stylesheet"/>
    <script src="/js/fontsmoothie.min.js"></script><!--[if lt IE 9]>
    <script src="/js/libs/html5shiv.min.js"></script>
    <script src="/js/libs/respond.min.js"></script><![endif]-->
</head>
<body>
<div id="header">
    <header>
        <div id="top">
            <div class="container">
                <div class="clearfix">
                    <div class="phone-social">
                        <ul class="social-link fl">
                            <li><a href="#"><i class="fa fa-weibo"></i></a></li>
                            <li><a href="#"><i class="fa fa-wechat"></i></a></li>
                        </ul>
                        <div class="phone fl"><a href="tel:"><i class="fa fa-phone"></i>400-636-9277</a></div>
                    </div>
                    <div class="top-link">
                        <ul>
                            <li><a href="#">帮助中心</a></li>
                            <li><a href="110.html">登录</a></li>
                            <li><a href="100.html">注册账户</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container clearfix">
            <div id="logo" class="fl"><a href="#"><img src="/img/logo.png"/></a></div>
            <nav role="navigation" class="navbar nav8 fr">
                <ul class="nav">
                    <li class="home active"><a href="index.html"><i class="fa fa-home"></i><span class="hidden-xs"> 乾道首页</span></a>
                    </li>
                    <li class=" dropdown"><a href="#x" role="button" data-hover="dropdown" class="dropdown-toggle">产品及服务</a>
                        <ul class="dropdown-menu">
                            <li><a href="/product/index">产品中心</a></li>
                            <li><a href="/team/index">业务团队</a></li>
                        </ul>
                    </li>
                    <li><a href="/safe/index">安全保障</a>
                    </li>
                    <li><a href="040.html">乾道研究</a>
                    </li>
                    <li><a href="/club/index">财富俱乐部</a>
                    </li>
                    <li><a href="/news/index">媒体中心</a>
                    </li>
                    <li><a href="/aboutus/index">关于我们</a>
                    </li>
                    <li><a href="080.html">公司公告</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header>
</div>