<div class="left-side sticky-left-side">

    <!--logo and iconic logo start-->
    <div class="logo">
        <a href="/admin_index"><img src="/admin/images/logo.png" alt=""></a>
    </div>

    <div class="logo-icon text-center">
        <a href="/admin_index"><img src="/admin/images/logo_icon.png" alt=""></a>
    </div>
    <!--logo and iconic logo end-->
    <div class="left-side-inner">

        <!-- visible to small devices only -->
        <div class="visible-xs hidden-sm hidden-md hidden-lg">
            <div class="media logged-user">
                <img alt="" src="/admin/images/photos/user-avatar.png" class="media-object">
                <div class="media-body">
                    <h4><a href="#">John Doe</a></h4>
                    <span>"Hello There..."</span>
                </div>
            </div>

            <h5 class="left-nav-title">Account Information</h5>
            <ul class="nav nav-pills nav-stacked custom-nav">
                <li><a href="#"><i class="fa fa-user"></i> <span>Profile</span></a></li>
                <li><a href="#"><i class="fa fa-cog"></i> <span>Settings</span></a></li>
                <li><a href="#"><i class="fa fa-sign-out"></i> <span>Sign Out</span></a></li>
            </ul>
        </div>

        <!--sidebar nav start-->
        <ul class="nav nav-pills nav-stacked custom-nav">
            <li><a href="/admin_index"><i class="fa fa-home"></i> <span>首页</span></a></li>
            <li class="menu-list nav-active"><a href=""><i class="fa fa-book"></i> <span>用户中心</span></a>
                <ul class="sub-menu-list">
                    <li class="active"><a href="/admin_user/edit" > 添加用户</a></li>
                    <li><a href="/admin_user"> 用户列表</a></li>
                </ul>
            </li>
            <li class="menu-list"><a href=""><i class="fa fa-cogs"></i> <span>产品中心</span></a>
                <ul class="sub-menu-list">
                    <li><a href="grids.html"> 产品中心</a></li>

                </ul>
            </li>
<!--            注意这里可无下拉列表-->
            <li><a href="fontawesome.html"><i class="fa fa-bullhorn"></i> <span>业务团队</span></a>
                <ul class="sub-menu-list">
                    <li><a href="gallery.html"> 业务团队</a></li>
                </ul>
            </li>

            <li class="menu-list"><a href=""><i class="fa fa-envelope"></i> <span>媒体中心</span></a>
                <ul class="sub-menu-list">
                    <li><a href="mail.html"> 新闻列表</a></li>
                </ul>
            </li>

            <li class="menu-list"><a href=""><i class="fa fa-tasks"></i> <span>企业文化</span></a>
                <ul class="sub-menu-list">
                    <li><a href="form_layouts.html">关于我们</a></li>
                    <li><a href="form_advanced_components.html"> 联系我们</a></li>
                </ul>
            </li>
            <li class="menu-list"><a href=""><i class="fa fa-bar-chart-o"></i> <span>财富俱乐部</span></a>
                <ul class="sub-menu-list">
                    <li><a href="flot_chart.html"> 列表</a></li>
                </ul>
            </li>
        </ul>
        <!--sidebar nav end-->

    </div>
</div>