<?php include APPLICATION_PATH."application/views/header.phtml" ?>
<div id="banner">
    <div style="background-image:url(/img/030banner.jpg)" class="banner"></div>
</div>
<section id="sub030" class="gray bb">
    <div class="heading s5">
        <h2>安全保障<small>Security and security</small></h2>
        <div class="line"></div>
    </div>
    <div class="space30">   </div>
    <div class="ss-item clearfix">
        <div class="col-sm-12 col-md-6 pic-item">
            <div class="img zoom"><a href="#"><img src="/img/030pic1.jpg"/></a></div>
        </div>
        <div class="clearfix"></div>
        <div class="desc-content">
            <div class="container">
                <div class="col-sm-12 col-md-6 desc-item">
                    <div class="dot"></div>
                    <div class="desc">
                        <h3>风险控制体系</h3>
                        <p class="el">美国一些科技、制药和能源巨头正在准备进，行一次大规模的游说活动，以争取一个免税期，使他们能以一个很高的贴现率，将自己存放在海外的约1万亿美元资金带回美国。这次活动目前仍处于计划阶段。不过据消息人士透露，这将是一次齐心协力的持久战，为了说服政策制定者，甲骨文。 </p><a href="#" class="btn">了解详情 <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ss-item clearfix even">
        <div class="col-sm-12 col-md-6 pic-item">
            <div class="img zoom"><a href="#"><img src="/img/030pic2.jpg"/></a></div>
        </div>
        <div class="clearfix"></div>
        <div class="desc-content">
            <div class="container">
                <div class="col-sm-12 col-md-6 desc-item">
                    <div class="dot"></div>
                    <div class="desc">
                        <h3>风险控制体系</h3>
                        <p class="el">美国一些科技、制药和能源巨头正在准备进，行一次大规模的游说活动，以争取一个免税期，使他们能以一个很高的贴现率，将自己存放在海外的约1万亿美元资金带回美国。这次活动目前仍处于计划阶段。不过据消息人士透露，这将是一次齐心协力的持久战，为了说服政策制定者，甲骨文。 </p><a href="#" class="btn">了解详情 <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ss-item clearfix">
        <div class="col-sm-12 col-md-6 pic-item">
            <div class="img zoom"><a href="#"><img src="/img/030pic3.jpg"/></a></div>
        </div>
        <div class="clearfix"></div>
        <div class="desc-content">
            <div class="container">
                <div class="col-sm-12 col-md-6 desc-item">
                    <div class="dot"></div>
                    <div class="desc">
                        <h3>风险控制体系</h3>
                        <p class="el">美国一些科技、制药和能源巨头正在准备进，行一次大规模的游说活动，以争取一个免税期，使他们能以一个很高的贴现率，将自己存放在海外的约1万亿美元资金带回美国。这次活动目前仍处于计划阶段。不过据消息人士透露，这将是一次齐心协力的持久战，为了说服政策制定者，甲骨文。 </p><a href="#" class="btn">了解详情 <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ss-item clearfix even">
        <div class="col-sm-12 col-md-6 pic-item">
            <div class="img zoom"><a href="#"><img src="/img/030pic4.jpg"/></a></div>
        </div>
        <div class="clearfix"></div>
        <div class="desc-content">
            <div class="container">
                <div class="col-sm-12 col-md-6 desc-item">
                    <div class="dot"></div>
                    <div class="desc">
                        <h3>风险控制体系</h3>
                        <p class="el">美国一些科技、制药和能源巨头正在准备进，行一次大规模的游说活动，以争取一个免税期，使他们能以一个很高的贴现率，将自己存放在海外的约1万亿美元资金带回美国。这次活动目前仍处于计划阶段。不过据消息人士透露，这将是一次齐心协力的持久战，为了说服政策制定者，甲骨文。 </p><a href="#" class="btn">了解详情 <i class="fa fa-angle-right"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include APPLICATION_PATH."application/views/footer.phtml" ?>
<script>
    $(document).ready(function(){
        $('.el').dotdotdot({
            ellipsis: '. . . ',
            watch: "window",
            wrap: 'letter',
        });
    })
</script>
</body>
</html>