<?php include APPLICATION_PATH."application/views/header.phtml" ?>
<div id="banner">
	<div style="background-image: url(/img/010banner.jpg)" class="index-banner">
		<div class="container"><a href="#" class="text"><img src="/img/010text.png"/></a></div>
	</div>
</div>
<section id="index01" class="gray1">
	<div class="container">
		<div class="clearfix su-items">
			<div class="col-xs-12 col-sm-6 col-md-3">
				<div class="heading5 square-box"><a href="#" class="over"></a>
					<h2>乾道财富优势<small>Superiority</small></h2>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 su-item-contain">
				<div class="su-item square-box"><a href="#" class="over"></a>
					<div class="desc">
						<div class="icon s1"><i class="trans"></i></div>
						<h3>稳健收益</h3>
						<p>乾道财富年化收益率</p>
						<p class="big">10%-15%</p>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 su-item-contain">
				<div class="su-item square-box"><a href="#" class="over"></a>
					<div class="desc">
						<div class="icon s2"><i class="trans"></i></div>
						<h3>安全保障</h3>
						<p>“3+1”风控体系</p>
						<p class="big">权威风险管理</p>
					</div>
				</div>
			</div>
			<div class="col-xs-12 col-sm-6 col-md-3 su-item-contain">
				<div class="su-item square-box"><a href="#" class="over"></a>
					<div class="desc">
						<div class="icon s3"><i class="trans"></i></div>
						<h3>管家服务</h3>
						<p>家庭财富管家提供</p>
						<p class="big">全程跟进式服务</p>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div id="project" class="clearfix">
		<div class="project-main">
			<div class="container">
				<div class="heading s1">
					<h3><a href="#">热投项目推荐<small>Hot projects recommended</small></a></h3>
				</div>
				<div class="lfnav"><a href="javascript:void(0);" id="lf-prev"><span class="icon-prev"><i></i></span></a><a href="javascript:void(0);" id="lf-next"><span class="icon-next"><i></i></span></a></div>
			</div>
		</div>
		<div class="col-xs-12 col-sm-6">
			<div class="lf-slide">
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic1.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic2.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic3.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic1.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic2.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic3.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic1.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic2.jpg"/></a></div>
				</div>
				<div class="item">
					<div class="img zoom"><a href="#"><img src="/img/010pic3.jpg"/></a></div>
				</div>
			</div>
		</div>
		<div class="clearfix"></div>
		<div class="white-bg">
			<div class="container"><a href="#" class="btn red">查看更多</a></div>
		</div>
		<div class="col-xs-12 col-sm-6 big-slide">
			<div class="fade-slide">
				<div class="item">
					<div style="background-image:url(/img/010fpic1.jpg)" class="imgbg"></div>
				</div>
				<div class="item">
					<div style="background-image:url(/img/010fpic2.jpg)" class="imgbg"></div>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="index02" class="gray clearfix">
	<div class="club-contain">
		<div class="container">
			<div class="col-sm-6 col-md-6">
				<div class="desc">
					<div class="heading s2">
						<h2><a href="#">乾道俱乐部<small>Qian dao club</small></a></h2>
					</div>
					<p>资产管理中心是乾道财富倾力打造的一支专业水平过硬、服务态度一流、致力于为广大投资群体实现财富保值增值的精英团队。团队核心成员均从事金融行业6年以上，投资经验丰富，且对目前金融市场的发展趋势以及各种理财产品都有着深刻认识和独到见解。团队成立以来累计服务客户已达千名，深得客户信任和业界好评。本着“融合、有为、专注、念和为您的财富梦想保驾护航！</p>
				</div>
			</div>
		</div>
	</div>
	<div class="col-sm-6 col-md-6 club-img">
		<div class="clearfix">
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="square-box more-r trans"><a href="#" class="over"></a>
					<div class="more"><span>了解详情<i class="fa fa-angle-double-right"></i></span></div>
				</div>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="club-item square-box"><a href="#" class="over"></a>
					<div class="hoverdir">
						<div><span>志趣相投1</span></div>
					</div><img src="/img/010club1.jpg"/>
				</div>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="club-item square-box"><a href="#" class="over"></a>
					<div class="hoverdir">
						<div><span>志趣相投2</span></div>
					</div><img src="/img/010club2.jpg"/>
				</div>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="club-item square-box"><a href="#" class="over"></a>
					<div class="hoverdir">
						<div><span>志趣相投3</span></div>
					</div><img src="/img/010club3.jpg"/>
				</div>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="club-item square-box"><a href="#" class="over"></a>
					<div class="hoverdir">
						<div><span>志趣相投4</span></div>
					</div><img src="/img/010club4.jpg"/>
				</div>
			</div>
			<div class="col-xs-6 col-sm-6 col-md-4">
				<div class="club-item square-box"><a href="#" class="over"></a>
					<div class="hoverdir">
						<div><span>志趣相投5</span></div>
					</div><img src="/img/010club5.jpg"/>
				</div>
			</div>
		</div>
	</div>
</section>
<section id="index03" class="gray">
	<div class="container">
		<div class="leg-container">
			<div class="clearfix">
				<div class="col-sm-12 col-md-8 col-lg-7">
					<div class="img zoom"><a href="#"><img src="/img/010bpic2.jpg" id="im"/></a></div>
				</div>
				<div class="col-sm-12 col-md-4 col-lg-5">
					<div class="heading s3 ss1">
						<h2><a href="#">媒体中心<small>Media Center</small></a></h2>
						<div class="more-box"><a href="#" class="more"><span>查看更多</span></a></div>
					</div>
					<div class="desc">
						<div class="news2-list">
							<ul>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">公司的专业投资团队从众多<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">公司的专业投资团队从众多优秀的未上市<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">乾道投资基金管理有限公司隶属于乾道<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">是一种在经济全球化背景下产生<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">在组合投资业务版块，乾道将侧重于私<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">公司的专业投资团队从众多优秀的未<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">是一种在经济全球化背景下产生的以创造<i class="date">2015-05-15</i></a></li>
								<li><a href="#" data-img="/img/010bpic2.jpg" data-target="#im">在组合投资业务版块，乾道将侧<i class="date">2015-05-15</i></a></li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="space50"></div>
</section>
<section id="index04" class="gray">
	<div class="heading s4">
		<h2><a href="#">合作伙伴<small>Cooperation Agency</small></a></h2>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
			<div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
				<div class="img zoom coo-img"><a href="#"><img src="/img/010coo1.jpg"/></a></div>
			</div>
		</div>
	</div>
	<div class="space50"></div>
</section>
<?php include APPLICATION_PATH.'/application/views/footer.phtml'?>
<script src="/js/jquery.hoverdir.min.js"></script>
<script>
	$(document).ready(function(){
		$("a[data-img]").hover(function(){
			target = $(this).attr("data-target");
			img = $(this).attr("data-img");
			$(target).addClass("ani");
			setTimeout(function(){
				$(target).attr("src",img);
			},500)
			setTimeout(function(){
				$(target).removeClass("ani");
			},1000)

		})
		$('.club-img .col-sm-6').each( function() { $(this).hoverdir(); } );
		$('.fade-slide').owlCarousel({
			animateOut: 'fadeOut',
			dots: false,
			nav: false,
			items: 1,
			autoplay: true,
			touchDrag: false,
			mouseDrag: false,
			loop: true,
			smartSpeed: 800,
		});
		var lf = $('.lf-slide').owlCarousel({
			dots: false,
			nav: false,
			items: 3,
			smartSpeed: 600,
		});
		$('#lf-next').click(function() {
			lf.trigger('next.owl.carousel');
		});
		$('#lf-prev').click(function() {
			lf.trigger('prev.owl.carousel');
		});
	})
	$('.el').dotdotdot({
		ellipsis: '. . . ',
		watch: "window",
		wrap: 'letter',
	});
</script>
<script src="/js/grayscale.js"></script>
<script>
	var isIE11 = !!navigator.userAgent.match(/Trident.*rv[ :]*11\./)
	if(isIE11){
		hovergray();
	}
	if (Function('/*@cc_on return document.documentMode===10@*/')()){
		hovergray();
	}
	function hovergray(){
		$(".coo-img img").hover(function(){
			grayscale($(this));
		},function(){
			grayscale.reset($(this));
		})
	}
</script>
</body>
</html>