<?php include APPLICATION_PATH.'/application/views/admin/head.phtml'?>
<body class="sticky-header">

<section>
    <!-- left side start-->
    <?php include APPLICATION_PATH.'/application/views/admin/left.phtml'?>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content" >

        <!-- header section start-->
        <?php include APPLICATION_PATH.'/application/views/admin/header.phtml'?>
        <!-- header section end-->

        <!--body wrapper start-->
        <div class="wrapper">
            <div class="row">
                <div class="col-md-6">
                    <!--statistics start-->
                    <div class="row state-overview">
                        <div class="col-md-6 col-xs-12 col-sm-6">
                            <div class="panel purple">
                                <div class="symbol">
                                    <i class="fa fa-gavel"></i>
                                </div>
                                <div class="state-value">
                                    <div class="value">230</div>
                                    <div class="title">New Order</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xs-12 col-sm-6">
                            <div class="panel red">
                                <div class="symbol">
                                    <i class="fa fa-tags"></i>
                                </div>
                                <div class="state-value">
                                    <div class="value">3490</div>
                                    <div class="title">Copy Sold</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row state-overview">
                        <div class="col-md-6 col-xs-12 col-sm-6">
                            <div class="panel blue">
                                <div class="symbol">
                                    <i class="fa fa-money"></i>
                                </div>
                                <div class="state-value">
                                    <div class="value">22014</div>
                                    <div class="title"> Total Revenue</div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6 col-xs-12 col-sm-6">
                            <div class="panel green">
                                <div class="symbol">
                                    <i class="fa fa-eye"></i>
                                </div>
                                <div class="state-value">
                                    <div class="value">390</div>
                                    <div class="title"> Unique Visitors</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--statistics end-->
                </div>
                <div class="col-md-6">
                    <!--more statistics box start-->
                    <div class="panel deep-purple-box">
                        <div class="panel-body">
                            <div class="row">
                                <div class="col-md-7 col-sm-7 col-xs-7">
                                    <div id="graph-donut" class="revenue-graph"></div>

                                </div>
                                <div class="col-md-5 col-sm-5 col-xs-5">
                                    <ul class="bar-legend">
                                        <li><span class="blue"></span> Open rate</li>
                                        <li><span class="green"></span> Click rate</li>
                                        <li><span class="purple"></span> Share rate</li>
                                        <li><span class="red"></span> Unsubscribed rate</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--more statistics box end-->
                </div>
            </div>
        </div>
        <!--body wrapper end-->

        <!--footer section start-->
        <?php include APPLICATION_PATH.'/application/views/admin/footer.phtml'?>
        <!--footer section end-->


    </div>
    <!-- main content end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
<script src="/admin/js/jquery-1.10.2.min.js"></script>
<script src="/admin/js/jquery-ui-1.9.2.custom.min.js"></script>
<script src="/admin/js/jquery-migrate-1.2.1.min.js"></script>
<script src="/admin/js/bootstrap.min.js"></script>
<script src="/admin/js/modernizr.min.js"></script>
<script src="/admin/js/jquery.nicescroll.js"></script>

<!--easy pie chart-->
<script src="/admin/js/easypiechart/jquery.easypiechart.js"></script>
<script src="/admin/js/easypiechart/easypiechart-init.js"></script>

<!--Sparkline Chart-->
<script src="/admin/js/sparkline/jquery.sparkline.js"></script>
<script src="/admin/js/sparkline/sparkline-init.js"></script>

<!--icheck -->
<script src="/admin/js/iCheck/jquery.icheck.js"></script>
<script src="/admin/js/icheck-init.js"></script>

<!-- jQuery Flot Chart-->
<script src="/admin/js/flot-chart/jquery.flot.js"></script>
<script src="/admin/js/flot-chart/jquery.flot.tooltip.js"></script>
<script src="/admin/js/flot-chart/jquery.flot.resize.js"></script>


<!--Morris Chart-->
<script src="/admin/js/morris-chart/morris.js"></script>
<script src="/admin/js/morris-chart/raphael-min.js"></script>

<!--Calendar-->
<script src="/admin/js/calendar/clndr.js"></script>
<script src="/admin/js/calendar/evnt.calendar.init.js"></script>
<script src="/admin/js/calendar/moment-2.2.1.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/underscore./admin/js/1.5.2/underscore-min.js"></script>

<!--common scripts for all pages-->
<script src="/admin/js/scripts.js"></script>

<!--Dashboard Charts-->
<script src="/admin/js/dashboard-chart-init.js"></script>


</body>
</html>
