<?php include APPLICATION_PATH."application/views/header.phtml" ?>
<div id="banner">
    <div style="background-image:url(/img/080banner.jpg)" class="banner"></div>
</div>
<section id="sub090" class="bb">
    <div class="container">
        <div class="heading3">
            <div class="breadcrumbs">
                <ul>
                    <li>您所在的位置： <a href="#">首页</a></li>
                    <li><a href="#">热投项目推荐</a></li>
                </ul>
            </div>
            <h2><a>热投项目推荐</a></h2>
        </div>
        <div class="space30"></div>
        <div class="article">
            <h1><a href="#">制造业新政将出</a></h1>
            <div class="info"><span>发布时间：2015-05-06 08:14</span><span>来源：经济观察报</span><span>作者：杜涛</span></div>
            <div class="arc-content">
                <p> 经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来；</p>
                <p>经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。</p>
                <p>4月28日，工信部总工程师王黎明在一季度信息发布会上透露称，“中国制造2025”总体方案已经通过国务院常务会议审议，将会很快发布。这是中国制造登上国家战略的标志。对于绝大多数传统制造业而言，这会是一次充满阵痛和艰难挑战；但对于10个早已被股市大风吹上天的行业来说，则会是另一个风口的开始。10大行业的投资机会据了解，王黎明所指的“中国制造2025”总体方案，暂定名为《“中国制造2025”规划纲要》。被写进其中的10大行业分别是：新一代信息技术产业、高档数控机床和机器人、航空航天装备、海洋工程装备及高技术船舶、先进轨道交通装备、节能与新能源汽车、电力装备、新材料、生物医药及高性能医疗设备、农业机械装备。工信部相关司局官员对经济观察报称，上述10大行业已经确认被写进“中国制造2025”，它们是中国在未来一段时间将着力推动、并力争取得突破发展的十大重点领域。这些行业的企业，尤其是那些领头企业将会获得包括工信部技改资金、专项发展资金在内，以及相关部委的一揽子财政支持，同时，这些领域的项目还有在立项、审批、推广等方面扶持政策。</p>
                <p> 经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来；</p>
                <p>经济观察报 记者 杜涛 对于中国规模庞大却又产能过剩的制造企业来说，最无奈的是，在风口四起的资本市场中，发现自己是没有故事可讲的人；而对于政府部门来说，更悲催的是想去带领中国制造业做一场华丽转型时，却发现很多制造企业已经是难上加难了。</p>
                <p>4月28日，工信部总工程师王黎明在一季度信息发布会上透露称，“中国制造2025”总体方案已经通过国务院常务会议审议，将会很快发布。这是中国制造登上国家战略的标志。对于绝大多数传统制造业而言，这会是一次充满阵痛和艰难挑战；但对于10个早已被股市大风吹上天的行业来说，则会是另一个风口的开始。10大行业的投资机会据了解，王黎明所指的“中国制造2025”总体方案，暂定名为《“中国制造2025”规划纲要》。被写进其中的10大行业分别是：新一代信息技术产业、高档数控机床和机器人、航空航天装备、海洋工程装备及高技术船舶、先进轨道交通装备、节能与新能源汽车、电力装备、新材料、生物医药及高性能医疗设备、农业机械装备。工信部相关司局官员对经济观察报称，上述10大行业已经确认被写进“中国制造2025”，它们是中国在未来一段时间将着力推动、并力争取得突破发展的十大重点领域。这些行业的企业，尤其是那些领头企业将会获得包括工信部技改资金、专项发展资金在内，以及相关部委的一揽子财政支持，同时，这些领域的项目还有在立项、审批、推广等方面扶持政策。</p>
            </div>
            <div class="article-bottom clearfix">
                <div class="col-xs-12 col-sm-12 col-md-6 fr">
                    <div class="share-box">分享到: <div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div></div>
                </div>
                <div class="col-xs-12 col-sm-12 col-md-6 fl">
                    <div class="next-article">
                        <ul>
                            <li><a href="#">上一篇：乾道财富热投项目</a></li>
                            <li><a href="#">下一篇：乾道财富的企业文化背景</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include APPLICATION_PATH.'/application/views/footer.phtml'?>
<script>
    $(document).ready(function(){
        $('.sub060-slide').owlCarousel({
            dots: true,
            nav: false,
            items: 1,
            smartSpeed: 650,
        });
        $('.el').dotdotdot({
            ellipsis: '. . .　　　　　　　　　　',
            watch: "window",
            wrap: 'letter',
        });
    })
</script>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"24"},"share":{},"image":{"viewList":["qzone","tsina","tqq","renren","weixin"],"viewText":"分享到：","viewSize":"16"},"selectShare":{"bdContainerClass":null,"bdSelectMiniList":["qzone","tsina","tqq","renren","weixin"]}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
</body>
</html>