<?php include APPLICATION_PATH."application/views/header.phtml" ?>
<div id="banner">
    <div style="background-image:url(/img/070banner.jpg)" class="banner"></div>
</div>
<section id="sub070-1" class="gray">
    <div class="heading s5">
        <h2>公司简介<small>Company profile</small></h2>
        <div class="line"></div>
    </div>
    <div class="space30"></div>
    <div class="container">
        <div class="row com-pro">
            <div class="col-xs-12 col-sm-6 col-md-5">
                <div class="border-img">
                    <div class="img zoom"><a href="#"><img src="/img/070pic1.jpg"/></a></div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-6 col-md-7">
                <div class="desc el">
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供更全面首选放心品重要年份乾道投资控股集团决定对九源财富更名为乾道财富资资金至3000万申请一系列金融特许牌集团的不断发展与壮为了树立更好的集团公司品牌形象以及提供更全面首选放心品牌”的重要年道投资控股集团决定对九源财富更名为乾道财富资产；</p>
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供更全面首选放心品重要年份乾道投资控股集团决定对九源财富更名为乾道财富资资金至3000万申请一系列金融特许牌集团的不断发展与壮为了树立更好的集团公司品牌形象以及提供更全面首选放心品牌”的重要年道投资控股集团决定对九源财富更名为乾道财富资产；</p>
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供更全面首选放心品重要年份乾道投资控股集团决定对九源财富更名为乾道财富资资金至3000万申请一系列金融特许牌集团的不断发展与壮为了树立更好的集团公司品牌形象以及提供更全面首选放心品牌”的重要年道投资控股集团决定对九源财富更名为乾道财富资产；</p>
                </div><a href="#" class="btn red fr">MORE <i class="fa fa-angle-double-right"></i></a>
            </div>
        </div>
        <div class="space50"></div>
    </div>
</section>
<section id="sub070-2" class="redbg">
    <div class="heading s5 ss1">
        <h2><a>企业文化<small>Enterprise culture</small></a></h2>
        <div class="line"></div>
    </div>
    <div class="space30"></div>
    <div class="container">
        <div class="cult scrollable">
            <div class="scrollbar">
                <div class="track">
                    <div class="thumb">
                        <div class="end"></div>
                    </div>
                </div>
            </div>
            <div class="viewport">
                <div class="overview">
                    <p>私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，首选放心品牌”的重要年份，乾道投资控股集团决定对九源财富更名为乾道资金至3000万元、并申请一系列金融特许牌照随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，资金至3000万元、并申请一系列金融特私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                    <p>私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，首选放心品牌”的重要年份，乾道投资控股集团决定对九源财富更名为乾道资金至3000万元、并申请一系列金融特许牌照随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，资金至3000万元、并申请一系列金融特私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                    <p>私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                    <p>随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，首选放心品牌”的重要年份，乾道投资控股集团决定对九源财富更名为乾道资金至3000万元、并申请一系列金融特许牌照随着集团的不断发展与壮大，为了树立更好的集团公司品牌形象以及提供，资金至3000万元、并申请一系列金融特私人银行业务在欧洲已有几百年历史，在大陆，正迎来新的发展机遇。私人银行业务不仅仅是顶级的财富管理服务，还广泛包括家族慈善、文化传承、留学移民等跨越空间、能经受时间考验的高品质服务。私人银行业务是乾道财富的战略发展重心，私人银行中心广纳英才，致力于提供一流的私人银行服务；</p>
                </div>
            </div>
        </div>
    </div>
    <div class="space50"></div>
</section>
<section id="sub070-3">
    <div class="heading s5">
        <h2><a>招贤纳士<small>recruiting</small></a></h2>
        <div class="line"></div>
    </div>
    <div class="space30"></div>
    <div class="container">
        <div class="row">
            <div class="recru-slide have-dots">
                <div class="item">
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理0</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理1</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理2</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理3</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理4</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理5</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理6</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理7</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理0</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理1</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理2</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理3</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理4</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理5</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理6</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理7</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理0</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理1</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理2</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理3</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理4</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理5</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理6</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-6 col-md-3">
                        <div class="recru-item"><a href="#" class="over"></a>
                            <div class="hoverdir">
                                <div><span>投资经理7</span></div>
                            </div>
                            <div class="img"><img src="/img/070recru.jpg"/></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="space30"></div>
</section>
<div class="up-down">
    <div class="line"></div>
    <ul>
        <li><a href="#"><i class="up"></i></a></li>
        <li><a href="#"><i class="down"></i></a></li>
    </ul>
</div>
<section id="sub070-4">
    <div class="heading s5">
        <h2><a>合作伙伴<small>Partners</small></a></h2>
        <div class="line"></div>
    </div>
    <div class="space30"></div>
    <div class="container">
        <div class="row">
            <div class="part2-slide have-dots">
                <div class="item">
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                </div>
                <div class="item">
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                    <div class="col-xs-6 col-sm-4 col-md-3 col-lg-2">
                        <div class="part2-item">
                            <div class="img"><a href="#"><img src="/img/070par.jpg"/></a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="space30"></div>
</section>
<section id="sub070-5">
    <div class="map-contain">
        <div id="map"></div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12 col-sm-5 col-md-4 fr">
                    <div class="contact-info">
                        <h2>乾道财富资产管理（北京）有限公司</h2>
                        <table>
                            <tr>
                                <td>地 址：</td>
                                <td>北京市东城区朝阳门内大街南竹杆胡同2号银河SOHO D座12层51215</td>
                            </tr>
                            <tr>
                                <td>邮 编：</td>
                                <td>100010</td>
                            </tr>
                            <tr>
                                <td>电 话：</td>
                                <td>010 - 56258008<br/>010 - 56258008</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<?php include APPLICATION_PATH.'/application/views/footer.phtml'?>
<script src="/js/jquery.tinyscrollbar.min.js"></script>
<script src="/js/jquery.hoverdir.min.js"></script>
<script>
    $(document).ready(function(){
        var $scrollbar = $(".scrollable");
        $scrollbar.tinyscrollbar({scrollInvert:true});
        var scrollbar = $scrollbar.data("plugin_tinyscrollbar");
        $(window).resize(function(){
            scrollbar.update();
        });
        $('.recru-slide').owlCarousel({
            dots: true,
            nav: false,
            items: 1,
            smartSpeed: 600,
        });
        $('.part2-slide').owlCarousel({
            dots: true,
            nav: false,
            items: 1,
            smartSpeed: 600,
        });
        $('.recru-slide .col-sm-6').each( function() { $(this).hoverdir(); } );
        $('.el').dotdotdot({
            ellipsis: '. . . ',
            watch: "window",
            wrap: 'letter',
        });
        var isIE11 = !!navigator.userAgent.match(/Trident.*rv[ :]*11\./)
        if(isIE11){
            hovergray();
        }
        if (Function('/*@cc_on return document.documentMode===10@*/')()){
            hovergray();
        }
        function hovergray(){
            $("body").append("<scr"+"ipt src='/js/grayscale.js'></scr"+"ipt>")
            $(".part2-item .img").each(function(){grayscale($(this));})
            $(".part2-item .img").hover(function(){
                grayscale.reset($(this));
            },function(){
                grayscale($(this));
            })
        }
    })
</script>
<script src="http://api.map.baidu.com/api?v=2.0&amp;ak=45f95152313df25a57c5fb0df72d400e"></script>
<script type="text/javascript">
    var map = new BMap.Map("map");
    map.centerAndZoom(new BMap.Point(116.440564,39.925557), 18);
    var pt = new BMap.Point(116.440564,39.925557);
    var opts = {type: BMAP_NAVIGATION_CONTROL_ZOOM}
    map.addControl(new BMap.NavigationControl(opts));
    var myIcon = new BMap.Icon("/img/location.png", new BMap.Size(30,80));
    var marker2 = new BMap.Marker(pt,{icon:myIcon});  // 创建标注
    map.addOverlay(marker2);
</script>
</body>
</html>
